name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build and push Docker image
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin 196437631690.dkr.ecr.us-east-1.amazonaws.com
        docker build -t 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:${{ github.sha }} ./app
        docker tag 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:${{ github.sha }} 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:latest
        docker push 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:${{ github.sha }}
        docker push 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:latest
    - name: Update manifest
      run: |
        sed -i "s|image: .*|image: 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app:${{ github.sha }}|g" k8s/app.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/app.yaml
        git diff --staged --quiet || git commit -m "Update image to ${{ github.sha }}"
        git push
    - name: Checkout AWS ECS Deploy GH Action
      uses: actions/checkout@v2
      with:
        repository: robertomoutinho/gh-action-ecs-deploy
       #token: ${{ github.token }}
        path: ./.github/actions/ecs-deploy  
    
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 196437631690.dkr.ecr.us-east-1.amazonaws.com

    - name: Deploy App to ECS Service
      uses: ./.github/actions/ecs-deploy
      with:
        app_repo_url: 196437631690.dkr.ecr.us-east-1.amazonaws.com/simple-app
        app_version: ${{ github.sha }}
        ecs_cluster: 'production1'
        ecs_service: 'web-app'
        ecs_container_name: 'web'
        aws_region: 'us-east-1'
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
